name: Update Repo 

on:
  workflow_call:
    inputs:
      upstream:
        type: string
        required: false
        description: The upstream repository. If omitted it is assumed the repo is not a fork and only submodules will be updated.
    outputs:
      new-commits:
        description: A boolean which is true if new commits were pushed to the repo.
        value: ${{ jobs.update-repo.outputs.new-commits }}

jobs:
  update-repo:
    runs-on: ubuntu-latest
    outputs:
      new-commits: ${{ steps.change-check.outputs.new-commits }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set Git Info
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Rebase
        if: ${{ inputs.upstream != '' }}
        run: |
          git remote add upstream https://github.com/${{ inputs.upstream }}.git
          git fetch upstream
          # https://stackoverflow.com/a/50056710/15752250
          git rebase upstream/$(git remote show upstream | sed -n '/HEAD branch/s/.*: //p')

      - name: Submodule Update
        run: |
          git submodule init
          git submodule update --remote --merge
          git commit -m "update submodule" -a || true

      - name: Check for Changes
        id: change-check
        run: |
          git fetch origin
          DEFAULT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
          echo "new-commits=$([[ $(git rev-parse $DEFAULT_BRANCH) != $(git rev-parse origin/$DEFAULT_BRANCH) ]] && echo true || echo false)" >> "$GITHUB_OUTPUT"

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force_with_lease: true
